### PR TITLE
Remove Fill Memory warnings

### LINKED ISSUE #2616: "Cannot read invalid region of memory" when using external memory.
Hello. When I'm using a `VkDeviceMemory`  with `VkImportMemoryFdInfoKHR` I'm getting an error:

> Cannot read invalid region of memory allocation 0x17 for bound Buffer object 0x16, please fill the memory before using.

In case if memory created with a flag `VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT` I have to make a dummy call to `vkMapMemory()` and `vkUnmapMemory()` to make this warning disappear. I didn't try to solve when the flag is `VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT`, but obviously mapping/unmapping will not work here.

There's of course an external memory, created with another device, which is updated separately.

### PR DESCRIPTION
**Pull request by mark-lunarg**
Implementation was incomplete -- when broken it produced incorrect warnings and when working produced non-specified warnings.  If this has a place in the future, it's in the assistant layer.

Fixes #2616.

### CODE REVIEW

**Comment by tobine** [comment]
clang-format error in CI

File: tests/layer_validation_tests.cpp [hunk 1]
```diff
@@ -1359,7 +1359,7 @@ TEST_F(VkLayerTest, ReservedParameter) {
     vkCreateEvent(device(), &event_info, NULL, &event_handle);
     m_errorMonitor->VerifyFound();
 }
-
+/*
```
Comment (chrisforbes) [inline tests/layer_validation_tests.cpp]: Why?

**Comment by tobine** [comment]
Killing all that code looks good. Just needs update to pass clang-format.

**Comment by mark-lunarg** [comment]
@chrisforbes, that's what I get for trying to work in an airport.  Restored the test, which I'd temporarily removed for local testing.  Also fixed c-f issue.
