### PR TITLE
Tobin gh605 mem valid per range

### LINKED ISSUE #605: vkCmdResolveImage generates invalid "Cannot read invalid memory..., please fill..." message
I'm converting a multisample image into a single sample one using vkCmdResolveImage, and getting an invalid validation layer error:

> vkCmdResolveImage(): Cannot read invalid memory 0x9, please fill the memory before using. (code: 12)

The previous render pass has two attachments, a multisample image (view) a multisample depth image (view):

```
  std::array<VkAttachmentDescription, 2> attachment_descriptions;
  // color image:
  attachment_descriptions[0].flags = 0;
  attachment_descriptions[0].format = /* some surface format */;
  attachment_descriptions[0].samples = VK_SAMPLE_COUNT_4_BIT;
  attachment_descriptions[0].loadOp = VK_ATTACHMENT_LOAD_OP_LOAD;
  attachment_descriptions[0].storeOp = VK_ATTACHMENT_STORE_OP_STORE;
  attachment_descriptions[0].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  attachment_descriptions[0].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  attachment_descriptions[0].initialLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
  attachment_descriptions[0].finalLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

  // depth image:
  attachment_descriptions[1].flags = 0;
  attachment_descriptions[1].format = /* some depth format */;
  attachment_descriptions[1].samples = VK_SAMPLE_COUNT_4_BIT;
  attachment_descriptions[1].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
  attachment_descriptions[1].storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE; // <-- CAUSING ERROR
  attachment_descriptions[1].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  attachment_descriptions[1].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  attachment_descriptions[1].initialLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;
  attachment_descriptions[1].finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;
```

Both views are later attached to a framebuffer and used in a render pass to draw something as usual, filling the whole image. The important part is, that I don't care for the depth image's content once the render pass is finished, so I set the storeOp of attachment 2 (index 1) to VK_ATTACHMENT_STORE_OP_DONT_CARE, while setting the color image's storeOp to VK_ATTACHMENT_STORE_OP_STORE. Once the render pass is done, I call vkCmdResolveImage (ignoring a few barriers in between). This generates the validation layer error from above.

When setting both storeOps to VK_ATTACHMENT_STORE_OP_STORE, the error is gone, even though the depth image's content isn't needed for resolving the multisample color image.

Both the color and the depth image are using the same memory object (0x9), but non-overlapping and well aligned regions within the memory object, respecting size and alignment of what vkGetImageMemoryRequirements says.

### PR DESCRIPTION
**Pull request by tobine**
This moves memory allocation valid tracking to be per-range instead of per allocation. Also improves alias tracking but lots more work to do in that department. It does fix a couple of errors in how invalid alias cases were being flagged.
This should fix #605 with current changes, but still need to fix the failing test.
Noted various holes with TODOs.

### CODE REVIEW

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -5303,38 +5303,81 @@ static bool print_memory_range_error(layer_data *dev_data, const uint64_t object
...
 static MEMORY_RANGE InsertMemoryRange(uint64_t handle, DEVICE_MEM_INFO *mem_info, VkDeviceSize memoryOffset,
-                                      VkMemoryRequirements memRequirements,
-                                      std::unordered_map<uint64_t, uint32_t> &handle_index_map) {
-    MEMORY_RANGE range;
+                                      VkMemoryRequirements memRequirements, bool is_image) {
+    //                                      std::unordered_map<uint64_t, uint32_t> &handle_index_map) {
+    MEMORY_RANGE range; // range to be inserted and returned
+    std::unordered_map<uint64_t, uint32_t> handle_index_map;
+    if (is_image) {
+        handle_index_map = mem_info->image_to_index_map;
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: This is a copy...

File: layers/core_validation.cpp [hunk 2]
```diff
@@ -5303,38 +5303,81 @@ static bool print_memory_range_error(layer_data *dev_data, const uint64_t object
...
+        range.image = true;
+    } else {
+        handle_index_map = mem_info->buffer_to_index_map;
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: ... and so is this ...

File: layers/core_validation.cpp [hunk 3]
```diff
@@ -5303,38 +5303,81 @@ static bool print_memory_range_error(layer_data *dev_data, const uint64_t object
...
+    // Update Memory aliasing prior to inserting new range
+    // TODO : Take into consideration padding for image/buffer aliasing
+    for (auto check_range : mem_info->bound_ranges) {
+        if (rangesIntersect(&range, check_range.start, check_range.end - check_range.start)) {
+            range.aliases.insert(&check_range);
+            check_range.aliases.insert(&range);
+        }
+    }
     mem_info->bound_ranges.push_back(range);
     handle_index_map[handle] = mem_info->bound_ranges.size() - 1;
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: ... so doing this modifies the local copy ...

File: layers/core_validation.cpp [hunk 4]
```diff
@@ -5303,38 +5303,81 @@ static bool print_memory_range_error(layer_data *dev_data, const uint64_t object
...
     return range;
 }
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: ... which evaporates here

File: layers/core_validation.cpp [hunk 5]
```diff
@@ -5303,38 +5303,81 @@ static bool print_memory_range_error(layer_data *dev_data, const uint64_t object
...
+    if (is_image) {
+        handle_to_index_map = &mem_info->image_to_index_map;
+    } else {
+        handle_to_index_map = &mem_info->buffer_to_index_map;
+    }
+    auto index = (*handle_to_index_map)[handle];
+    auto erase_range = mem_info->bound_ranges[index];
+    for (auto alias_range : erase_range.aliases) {
+        alias_range->aliases.erase(&erase_range);
+        erase_range.aliases.erase(alias_range);
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: This method of tracking aliasing doesn't really sit well. I think it needs some discussion

File: layers/core_validation.cpp [hunk 6]
```diff
@@ -5303,38 +5303,81 @@ static bool print_memory_range_error(layer_data *dev_data, const uint64_t object
...
+//  map and clean up any aliases for range being removed.
+static void RemoveMemoryRange(uint64_t handle, DEVICE_MEM_INFO *mem_info, bool is_image) {
+    std::unordered_map<uint64_t, uint32_t> *handle_to_index_map;
+    if (is_image) {
+        handle_to_index_map = &mem_info->image_to_index_map;
+    } else {
+        handle_to_index_map = &mem_info->buffer_to_index_map;
+    }
+    auto index = (*handle_to_index_map)[handle];
+    auto erase_range = mem_info->bound_ranges[index];
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: This is a copy ...

File: layers/core_validation.cpp [hunk 7]
```diff
@@ -5303,38 +5303,81 @@ static bool print_memory_range_error(layer_data *dev_data, const uint64_t object
...
+    for (auto alias_range : erase_range.aliases) {
+        alias_range->aliases.erase(&erase_range);
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: ... so taking its address here is the address of an object on the stack, which is unlikely to be useful to remove.

File: layers/core_validation_types.h [hunk 8]
```diff
@@ -208,9 +208,12 @@ struct MemRange {
 
 struct MEMORY_RANGE {
     uint64_t handle;
+    bool image; // True for image, false for buffer
     VkDeviceMemory memory;
     VkDeviceSize start;
     VkDeviceSize end;
+    // Set of ptrs to every range aliased with this one
+    std::unordered_set<MEMORY_RANGE *> aliases;
```
Comment (chrisforbes) [inline layers/core_validation_types.h]: These are intended to be pointers into `DEVICE_MEM_INFO::bound_ranges`, which is a vector. Unfortunately, later inserts into that same vector invalidate them all...

File: layers/core_validation.cpp [hunk 9]
```diff
@@ -5303,38 +5303,81 @@ static bool print_memory_range_error(layer_data *dev_data, const uint64_t object
...
+        handle_index_map = mem_info->buffer_to_index_map;
+        range.image = false;
+    }
     range.handle = handle;
     range.memory = mem_info->mem;
     range.start = memoryOffset;
     range.end = memoryOffset + memRequirements.size - 1;
+    // Update Memory aliasing prior to inserting new range
+    // TODO : Take into consideration padding for image/buffer aliasing
+    for (auto check_range : mem_info->bound_ranges) {
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: (2) This is a copy...

File: layers/core_validation.cpp [hunk 10]
```diff
@@ -5303,38 +5303,81 @@ static bool print_memory_range_error(layer_data *dev_data, const uint64_t object
...
+        if (rangesIntersect(&range, check_range.start, check_range.end - check_range.start)) {
+            range.aliases.insert(&check_range);
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: (2) ... so this is inserting the address of a stack object, which isn't what you want.

File: layers/core_validation.cpp [hunk 11]
```diff
@@ -5303,38 +5303,81 @@ static bool print_memory_range_error(layer_data *dev_data, const uint64_t object
...
+            check_range.aliases.insert(&range);
+        }
+    }
     mem_info->bound_ranges.push_back(range);
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: (2) ... and here push_back potentially invalidates all the pointers you'd intended to insert into the aliases sets, as it may have to reallocate the backing memory to grow.

File: layers/core_validation.cpp [hunk 12]
```diff
@@ -5303,38 +5303,81 @@ static bool print_memory_range_error(layer_data *dev_data, const uint64_t object
...
+    } else {
+        handle_to_index_map = &mem_info->buffer_to_index_map;
+    }
+    auto index = (*handle_to_index_map)[handle];
+    auto erase_range = mem_info->bound_ranges[index];
+    for (auto alias_range : erase_range.aliases) {
+        alias_range->aliases.erase(&erase_range);
+        erase_range.aliases.erase(alias_range);
+    }
+    mem_info->bound_ranges.erase(mem_info->bound_ranges.begin() + index);
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: ... same problem as the push_back marked (2) above.

File: layers/core_validation.cpp [hunk 13]
```diff
@@ -5272,86 +5272,99 @@ static bool validateIdleBuffer(const layer_data *my_data, VkBuffer buffer) {
...
+    return true;
 }
-
-static MEMORY_RANGE InsertMemoryRange(uint64_t handle, DEVICE_MEM_INFO *mem_info, VkDeviceSize memoryOffset,
-                                      VkMemoryRequirements memRequirements, bool is_image) {
-    //                                      std::unordered_map<uint64_t, uint32_t> &handle_index_map) {
+// Simplified rangesIntersect that calls above function with limited params
+static bool rangesIntersect(layer_data const *dev_data, MEMORY_RANGE const *range1, VkDeviceSize offset, VkDeviceSize size) {
+    // Create a local MEMORY_RANGE struct to wrap offset/size
+    MEMORY_RANGE range_wrap;
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: Bit unfortunate that this temporary wrapper now contains an unordered_set... :(

File: layers/core_validation.cpp [hunk 14]
```diff
@@ -5272,86 +5272,99 @@ static bool validateIdleBuffer(const layer_data *my_data, VkBuffer buffer) {
...
     MEMORY_RANGE range; // range to be inserted and returned
     std::unordered_map<uint64_t, uint32_t> handle_index_map;
-    if (is_image) {
-        handle_index_map = mem_info->image_to_index_map;
-        range.image = true;
-    } else {
-        handle_index_map = mem_info->buffer_to_index_map;
-        range.image = false;
-    }
+    handle_index_map = is_image ? mem_info->image_to_index_map : mem_info->buffer_to_index_map;
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: This doesn't fix the complaint in previous commit -- you need ptr or ref. Converting to a single assignment like this does let you use ref though, so there's a win...

File: layers/core_validation.cpp [hunk 15]
```diff
@@ -5333,8 +5333,6 @@ static bool InsertMemoryRange(layer_data const *dev_data, uint64_t handle, DEVIC
                               VkMemoryRequirements memRequirements, bool is_image, bool is_linear) {
     bool skip_call = false;
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: Alright, this solves the bulk of the problems noted earlier.

File: layers/core_validation.cpp [hunk 16]
```diff
@@ -5341,17 +5341,24 @@ static bool InsertMemoryRange(layer_data const *dev_data, uint64_t handle, DEVIC
...
+    range.aliases.clear();
+    // Update Memory aliasing
+    // Save aliase ranges so we can copy into final map entry below. Can't do it in loop b/c we don't yet have final ptr. If we
+    // inserted into map before loop to get the final ptr, then we may enter loop when not needed & we check range against itself
+    std::unordered_set<MEMORY_RANGE *> tmp_alias_ranges;
     for (auto &obj_range_pair : mem_info->bound_ranges) {
-        bool intersection_error = false;
         auto check_range = &obj_range_pair.second;
+        bool intersection_error = false;
         if (rangesIntersect(dev_data, &range, check_range, intersection_error)) {
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: Per style guide, we shouldn't be using ref-to-nonconst as an out parameter. It's not immediately clear at this call site that `intersection_error` is written by `rangesIntersect`. Pass it by ptr instead?

File: layers/core_validation.cpp [hunk 17]
```diff
@@ -5378,8 +5385,8 @@ static void RemoveMemoryRange(uint64_t handle, DEVICE_MEM_INFO *mem_info, bool i
     auto erase_range = &mem_info->bound_ranges[handle];
     for (auto alias_range : erase_range->aliases) {
         alias_range->aliases.erase(erase_range);
-        erase_range->aliases.erase(alias_range);
     }
+    erase_range->aliases.clear();
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: Don't even need to do this-- it's going away in the next line.

File: layers/core_validation.cpp [hunk 18]
```diff
@@ -5341,17 +5341,24 @@ static bool InsertMemoryRange(layer_data const *dev_data, uint64_t handle, DEVIC
     range.start = memoryOffset;
     range.size = memRequirements.size;
     range.end = memoryOffset + memRequirements.size - 1;
-    // Update Memory aliasing prior to inserting new range
+    range.aliases.clear();
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: This /ought/ to be spurious, unless `MEMORY_RANGE` doesn't construct properly?

File: layers/core_validation.cpp [hunk 19]
```diff
@@ -5341,17 +5341,24 @@ static bool InsertMemoryRange(layer_data const *dev_data, uint64_t handle, DEVIC
...
+    // Update Memory aliasing
+    // Save aliase ranges so we can copy into final map entry below. Can't do it in loop b/c we don't yet have final ptr. If we
+    // inserted into map before loop to get the final ptr, then we may enter loop when not needed & we check range against itself
+    std::unordered_set<MEMORY_RANGE *> tmp_alias_ranges;
     for (auto &obj_range_pair : mem_info->bound_ranges) {
-        bool intersection_error = false;
         auto check_range = &obj_range_pair.second;
+        bool intersection_error = false;
         if (rangesIntersect(dev_data, &range, check_range, intersection_error)) {
             skip_call |= intersection_error;
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: It would be nice if the rest of the side effects were skipped if you're going to skip the call...

File: layers/core_validation.cpp [hunk 20]
```diff
@@ -5310,18 +5312,32 @@ static bool rangesIntersect(layer_data const *dev_data, MEMORY_RANGE const *rang
     // Ranges intersect
     return true;
 }
-// Simplified rangesIntersect that calls above function with limited params
-static bool rangesIntersect(layer_data const *dev_data, MEMORY_RANGE const *range1, VkDeviceSize offset, VkDeviceSize size) {
+// Simplified rangesIntersect that calls above function with limited params: base_address to start at and size to consider
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: These names `base_address`, `size` don't agree with the actual parameters, `offset` and `end`

File: layers/core_validation.cpp [hunk 21]
```diff
@@ -5310,18 +5312,32 @@ static bool rangesIntersect(layer_data const *dev_data, MEMORY_RANGE const *rang
...
-
+// For given mem_info, set all ranges valid that intersect [offset-end] range
+// TODO : For ranges where there is no alias, we may want to create new buffer ranges that are valid
+static void SetMemRangesValid(layer_data const *dev_data, DEVICE_MEM_INFO const *mem_info, VkDeviceSize offset, VkDeviceSize end) {
+    bool tmp_bool = false;
+    MEMORY_RANGE map_range;
+    map_range.linear = true;
+    map_range.start = offset;
+    map_range.end = end;
+    for (auto handle_range_pair : mem_info->bound_ranges) {
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: Probably `auto &`, this is doing a lot of copying...

File: layers/core_validation.cpp [hunk 22]
```diff
@@ -10200,11 +10228,13 @@ MapMemory(VkDevice device, VkDeviceMemory mem, VkDeviceSize offset, VkDeviceSize
...
     VkResult result = VK_ERROR_VALIDATION_FAILED_EXT;
     std::unique_lock<std::mutex> lock(global_lock);
-#if MTMERGESOURCE
-    DEVICE_MEM_INFO *pMemObj = getMemObjInfo(dev_data, mem);
-    if (pMemObj) {
-        pMemObj->valid = true;
-        if ((dev_data->phys_dev_mem_props.memoryTypes[pMemObj->alloc_info.memoryTypeIndex].propertyFlags &
+    DEVICE_MEM_INFO *mem_info = getMemObjInfo(dev_data, mem);
+    if (mem_info) {
+        auto end_address = (VK_WHOLE_SIZE == size) ? mem_info->alloc_info.allocationSize - 1 : offset + size - 1;
```
Comment (chrisforbes) [inline layers/core_validation.cpp]: nitpick: end_offset? This isn't an address yet...

File: layers/core_validation_types.h [hunk 23]
```diff
@@ -221,7 +222,8 @@ struct MEMORY_RANGE {
 // Data struct for tracking memory object
 struct DEVICE_MEM_INFO {
     void *object; // Dispatchable object used to create this memory (device of swapchain)
-    bool valid; // Stores if the color/depth/buffer memory has valid data or not
+    // bool valid; // Stores if the color/depth/buffer memory has valid data or not
+    // TODO : What to do with this guy in migrating valid to range?
     bool stencil_valid; // TODO: Stores if the stencil memory has valid data or not. The validity of this memory may ultimately need
```
Comment (chrisforbes) [inline layers/core_validation_types.h]: This is a bit of a headscratcher.

**Comment by tobine** [comment]
Pushed some changes to address @chrisforbes feedback and also fixed the test issue that was causing crash on one test. This branch is now clean on the farm so I'd like to merge it if I can get an "all-clear" review.

**Comment by chrisforbes** [comment]
@tobine I'd consider squashing some of this down as the intermediate states I made a bunch of noise about early in the series are /really/ busted.

Other than that, :+1: from me.
