### PR TITLE
Fix multi-plane aspect bit check

### LINKED ISSUE #2527: Multiplanar aspect flags are still reporting an error
This is a duplicate of #2378 but because I can't reopen it I'm creating a new one.

The issue is that whenever the aspect flags are checked, the validation layer does not yet recognize the multiplanae aspect flags (VK_IMAGE_ASPECT_PLANE_0_BIT and so on) as valid and prints the following error:

> vkCreateImageView(): Color image formats must have the VK_IMAGE_ASPECT_COLOR_BIT set. The spec valid usage text states 'aspectMask must be a valid combination of VkImageAspectFlagBits values' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageSubresource-aspectMask-parameter)

>vkCmdPipelineBarrier(): Color image formats must have the VK_IMAGE_ASPECT_COLOR_BIT set. The spec valid usage text states 'aspectMask must be a valid combination of VkImageAspectFlagBits values' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageSubresource-aspectMask-parameter)

The issue occurs with current git master (37beb71e6fdb90d1bf40089abf98bb3c).

### PR DESCRIPTION
**Pull request by daveh-lunarg**
The FormatIsColor() util fxn classified anything not depth or stencil as 'color', and applied the aspect bit checks correspondingly. This PR segregates multi-plane formats from the catch-all color classification and adds multi-plane specific aspect bit checks for them.

Resolves #2527.

### CODE REVIEW

File: layers/buffer_validation.cpp [hunk 1]
```diff
@@ -3238,6 +3238,25 @@ bool ValidateImageAspectMask(layer_data *device_data, VkImage image, VkFormat fo
                             "%s: Stencil-only image formats can have only the VK_IMAGE_ASPECT_STENCIL_BIT set. %s", func_name,
                             validation_error_map[VALIDATION_ERROR_0a400c01]);
         }
+    } else if (FormatIsMultiplane(format)) {
```
Comment (jzulauf-lunarg) [inline layers/buffer_validation.cpp]: This handling is somewhat different (at least for barriers) if the image is disjoint, where more than one can be specified... https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VUID-VkImageMemoryBarrier-image-01672

Comment (daveh-lunarg) [reply layers/buffer_validation.cpp]: Y'know, back in my day a man'd do one kind of aspectMask validation on an image, whether he was settin' up a memory barrier or creatin' an imageView.  Didn't matter, we just had one kind and it was good enough for whatever you needed. Then these kids come along with their multi-plane images and YCbCr conversions.....   bah! 

Anyway, good catch @jzulauf-lunarg! I'll take this one back to the drawing board...

**Comment by daveh-lunarg** [comment]
For purpose of resolving this issue, it's sufficient just to exclude the multi-plane formats from categorization by the FormatIsColor() util function.  I've loosened the multi-plane checks in ValidateImageAspectMask() to just verify that all aspectMask bits are within the overall allowed subset.  There are specific VUIDs that capture the different requirements for barriers and image views that (will, soon) provide the domain-specific validation of the aspect mask.

File: layers/buffer_validation.cpp [hunk 2]
```diff
@@ -3147,6 +3147,18 @@ bool ValidateImageAspectMask(layer_data *device_data, VkImage image, VkFormat fo
                             HandleToUint64(image), VALIDATION_ERROR_0a400c01,
                             "%s: Stencil-only image formats can have only the VK_IMAGE_ASPECT_STENCIL_BIT set.", func_name);
         }
+    } else if (FormatIsMultiplane(format)) {
```
Comment (jzulauf-lunarg) [inline layers/buffer_validation.cpp]: This version has the benefit of brevity -- however, when you flesh out the rest of the domain specific checks, it's going to get bigger.  I think this is the right balance of providing initial coverage while avoiding "false positives".

File: layers/buffer_validation.cpp [hunk 3]
```diff
@@ -3147,6 +3147,18 @@ bool ValidateImageAspectMask(layer_data *device_data, VkImage image, VkFormat fo
...
+        if (3 == FormatPlaneCount(format)) {
+            valid_flags = valid_flags | VK_IMAGE_ASPECT_PLANE_2_BIT;
+        }
+        if ((aspect_mask & valid_flags) != aspect_mask) {
+            skip |= log_msg(report_data, VK_DEBUG_REPORT_ERROR_BIT_EXT, VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_EXT,
+                            HandleToUint64(image), VALIDATION_ERROR_0a400c01,
+                            "%s: Multi-plane image formats may have only VK_IMAGE_ASPECT_COLOR_BIT or VK_IMAGE_ASPECT_PLANE_n_BITs "
+                            "set, where n = [0, 1, 2].",
+                            func_name);
+        }
```
Comment (jzulauf-lunarg) [inline layers/buffer_validation.cpp]: the [0... n] range could be set with a const char assignment overwritten in the '(3 ==' clause to get a more accurate message, but I don't know if it's worth re-spinning the PR for.
